name: Run Web Scraping

on:
  schedule:
    - cron: '0 0 * * 0'  # This schedule is for running every Sunday at midnight
  workflow_dispatch:

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest  # Specifies the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks-out your repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: pip install -r requirements.txt  # Install dependencies

    - name: Run the script
      run: python Flatmates_Scraper.py  # Run your script
      env:
        GSPREAD_CREDENTIALS: ${{ secrets.GSPREAD_CREDENTIALS }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}  # Assuming you also have this secret set

